### ISSUE TITLE
Unable to lasertag on Ubuntu

### ISSUE THREAD

**Issue by ragunathjawahar** [cesarferreira/lasertag#1]
Hi, I have a new git repo. With just one commit. When I try to run `lasertag` on it,

`sudo lasertag --path ./todoapp-mvp --module app -d`

I get the following,

`Something went wrong so I stopped all the madness!!`

I am not sure which step has failed.

**Update**
Looks like it fails here...

```
def assemble_command
    "gradle :#{@app_module}:assemble#{(@app_flavor or "").capitalize}Release"
end
```

The script requires a `gradle` installation. Wouldn't it be nice to use the gradle wrapper `gradlew` available in the project for assembling? We could use `gradlew` by default and use  `gradle` as a fallback. Which is very unlikely for most Android projects.

**Comment by cesarferreira** [comment]
Hey!
I tried like you said to use the gradle as a fallback but sometimes people have faulty gradle wraps and missing files, I ended up using the gradle runtime because I know it will not fail.

You just have to do a `apt-get install gradle` and not worry about it anymore :)
